export const body = {
  address: "",
  attachments: [
    {
      imgPath: "",
    },
  ],
  categoryId: 0,
  city: "",
  componentsDto: {
    // additional: "",
    airCondition: false,
    courtyard: false,
    furniture: false,
    gasStove: false,
    internet: false,
    tv: false,
  },
  country: "",
  description: "",
  homeAmenitiesDto: {
    // additional: "",
    busStop: false,
    garden: false,
    market: false,
    park: false,
    parking: false,
    school: false,
    stadium: false,
    subway: false,
    superMarket: false,
  },
  houseDetails: {
    area: null,
    bath: null,
    beds: null,
    garage: null,
    room: null,
    yearBuilt: null,
  },
  locations: {
    latitude: 41.311081,
    longitude: 69.240562,
  },
  name: "",
  price: null,
  region: "",
  salePrice: null,
  status: true,
  zipCode: "",
};
